import { Inter } from "next/font/google";
import "./globals.css";
import MyContext from "@/Helper/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next js app",
};

export default function RootLayout({ children }) {
  MyContext
  return (
    <html lang="en">
      <body>
        <MyContext>
          {children}
        </MyContext>
      </body>
    </html>
  );
}
